language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl -I ./lib/ Makefile.PL
  - make
  - make test
  - cover -test

after_success:
  - travis_retry cover -report codecov
